# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Donald/Documents/space_invader2/project_1/project_1.cache/wt [current_project]
set_property parent.project_path C:/Users/Donald/Documents/space_invader2/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/Donald/Documents/space_invader2/project_1/project_1.srcs/sources_1/imports/new/Binary_To_BCD.v
  C:/Users/Donald/Documents/space_invader2/project_1/project_1.srcs/sources_1/imports/new/ClkDiv_66_67kHz.v
  C:/Users/Donald/Documents/space_invader2/project_1/project_1.srcs/sources_1/imports/new/SPImode0.v
  C:/Users/Donald/Documents/space_invader2/project_1/project_1.srcs/sources_1/imports/new/spiCtrl.v
  C:/Users/Donald/Documents/space_invader2/project_1/project_1.srcs/sources_1/imports/new/ClkDiv_5Hz.v
  C:/Users/Donald/Documents/space_invader2/project_1/project_1.srcs/sources_1/imports/new/PmodJSTK.v
  C:/Users/Donald/Documents/space_invader2/project_1/project_1.srcs/sources_1/imports/new/clock_div.v
  C:/Users/Donald/Documents/space_invader2/project_1/project_1.srcs/sources_1/imports/new/pmod_step_driver.v
  C:/Users/Donald/Documents/space_invader2/project_1/project_1.srcs/sources_1/imports/new/ssdCtrl.v
  C:/Users/Donald/Documents/space_invader2/project_1/project_1.srcs/sources_1/imports/new/PmodJSTK_Demo.v
  C:/Users/Donald/Documents/space_invader2/project_1/project_1.srcs/sources_1/imports/new/jstk_data_decoder.v
  C:/Users/Donald/Documents/space_invader2/project_1/project_1.srcs/sources_1/imports/new/pmod_step_interface.v
  C:/Users/Donald/Documents/space_invader2/project_1/project_1.srcs/sources_1/imports/new/jstksteptop.v
}
read_vhdl -library xil_defaultlib {
  C:/Users/Donald/Documents/space_invader2/project_1/project_1.srcs/sources_1/imports/new/mux.vhd
  C:/Users/Donald/Documents/space_invader2/project_1/project_1.srcs/sources_1/imports/new/pc.vhd
  C:/Users/Donald/Documents/space_invader2/project_1/project_1.srcs/sources_1/imports/new/ALU.vhd
  C:/Users/Donald/Documents/space_invader2/project_1/project_1.srcs/sources_1/imports/new/ALU_MUX.vhd
  C:/Users/Donald/Documents/space_invader2/project_1/project_1.srcs/sources_1/imports/new/ControlUnit.vhd
  C:/Users/Donald/Documents/space_invader2/project_1/project_1.srcs/sources_1/imports/new/Flag_Reg_c.vhd
  C:/Users/Donald/Documents/space_invader2/project_1/project_1.srcs/sources_1/imports/new/Flag_Reg_z.vhd
  C:/Users/Donald/Documents/space_invader2/project_1/project_1.srcs/sources_1/imports/new/RegisterFile.vhd
  C:/Users/Donald/Documents/space_invader2/project_1/project_1.srcs/sources_1/imports/new/Scratch_Pad_Mux.vhd
  C:/Users/Donald/Documents/space_invader2/project_1/project_1.srcs/sources_1/imports/new/Scratch_RAM.vhd
  C:/Users/Donald/Documents/space_invader2/project_1/project_1.srcs/sources_1/imports/new/Stack_Pointer.vhd
  C:/Users/Donald/Documents/space_invader2/project_1/project_1.srcs/sources_1/imports/new/VGAdrive.vhd
  C:/Users/Donald/Documents/space_invader2/project_1/project_1.srcs/sources_1/imports/new/counter_for_one_shot.vhd
  C:/Users/Donald/Documents/space_invader2/project_1/project_1.srcs/sources_1/imports/new/flag_mux.vhd
  C:/Users/Donald/Documents/space_invader2/project_1/project_1.srcs/sources_1/imports/new/int_input.vhd
  C:/Users/Donald/Documents/space_invader/space_invader/prog_rom.vhd
  C:/Users/Donald/Documents/space_invader2/project_1/project_1.srcs/sources_1/imports/new/program_counter.vhd
  C:/Users/Donald/Documents/space_invader2/project_1/project_1.srcs/sources_1/imports/new/ram2k_8.vhd
  C:/Users/Donald/Documents/space_invader2/project_1/project_1.srcs/sources_1/imports/new/reg_mux.vhd
  C:/Users/Donald/Documents/space_invader2/project_1/project_1.srcs/sources_1/imports/new/scr_data_mux.vhd
  C:/Users/Donald/Documents/space_invader2/project_1/project_1.srcs/sources_1/imports/new/shad_flag_reg_c.vhd
  C:/Users/Donald/Documents/space_invader2/project_1/project_1.srcs/sources_1/imports/new/shad_flag_reg_z.vhd
  C:/Users/Donald/Documents/space_invader2/project_1/project_1.srcs/sources_1/imports/new/vga_clk_div.vhd
  C:/Users/Donald/Documents/space_invader2/project_1/project_1.srcs/sources_1/imports/new/7_Seg.vhd
  C:/Users/Donald/Documents/space_invader2/project_1/project_1.srcs/sources_1/imports/new/RATCPU.vhd
  C:/Users/Donald/Documents/space_invader2/project_1/project_1.srcs/sources_1/imports/new/clk_div.vhd
  C:/Users/Donald/Documents/space_invader2/project_1/project_1.srcs/sources_1/imports/new/debounce_one_shot_FSM.vhd
  C:/Users/Donald/Documents/space_invader2/project_1/project_1.srcs/sources_1/imports/new/vgaDriverBuffer.vhd
  C:/Users/Donald/Documents/space_invader2/project_1/project_1.srcs/sources_1/imports/new/RatCPUWrapper.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Donald/Documents/space_invader2/project_1/project_1.srcs/constrs_1/new/Constraints.xdc
set_property used_in_implementation false [get_files C:/Users/Donald/Documents/space_invader2/project_1/project_1.srcs/constrs_1/new/Constraints.xdc]


synth_design -top RAT_wrapper -part xc7a35tcpg236-1


write_checkpoint -force -noxdef RAT_wrapper.dcp

catch { report_utilization -file RAT_wrapper_utilization_synth.rpt -pb RAT_wrapper_utilization_synth.pb }
